---
- name: Submit JCL
  ibm.ibm_zos_core.zos_job_submit:
    src: "{{ src }}"
  register: zos_job_run_job_output

- name: Validate return code
  ansible.builtin.assert:
    that:
      - zos_job_run_job_output.jobs[0].ret_code.code <= acceptable_cond_code
