---
# debug
- name: Show library
  ansible.builtin.debug:
    var: library
# end debug

- name: Find members for {{ library }}
  ansible.builtin.find:
    paths: "{{ seed_base }}/{{ library }}"
    recurse: false
    file_type: file
  delegate_to: localhost
  register: zos_seed_library_member_files

# debug
- name: Show members found
  ansible.builtin.debug:
    var: zos_seed_library_member_files.files
# end debug

- name: Copy members
  ansible.builtin.include_tasks: copy_members.yml
  loop: "{{ zos_seed_library_member_files.files }}"
  loop_control:
    loop_var: member
