---
all:
  children:
    zos:
      hosts:
        zoslab:
          ansible_host: 173.45.66.189

        zosbad:
          ansible_host: 173.45.66.188

      vars:
        ansible_python_interpreter: /usr/lpp/IBM/cyp/v3r11/pyz/bin/python

        zoau: /usr/lpp/IBM/zoautil
        pyz: /usr/lpp/IBM/cyp/v3r11/pyz
        file_xfer_dir: ../data

        environment_vars:
          ZOAU_HOME: "{{ ZOAU }}"
          PATH: "{{ ZOAU }}/bin:{{ PYZ }}/bin:/bin:/var/bin"
          LIBPATH: "{{ ZOAU }}/lib:{{ PYZ }}/lib:/lib:/usr/lib:."
          PYTHONPATH: "{{ ZOAU }}/lib/3.11"

          PYTHONIOENCODING: utf-8
          PYTHONSTDINENCODING: cp1047

          _BPXK_AUTOCVT: ON
          _CEE_RUNOPTS: FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)
          _TAG_REDIR_ERR: txt
          _TAG_REDIR_IN: txt
          _TAG_REDIR_OUT: txt

          LANG: C
