---
- name: Ping z/OS node
  hosts: zos
  gather_facts: false
  environment: "{{ environment_vars }}"

  tasks:
    - name: Pinging host
      ansible.builtin.ping: {}
      register: result

    - name: Response
      ansible.builtin.debug:
        msg: "{{ result.ping }}"
