name: Ansible Linter Workflow

on:
  push:
    branches-ignore: [main]    # Runs on pushes to ANY branch except main
  pull_request:
    branches: [main]           # Runs on PRs targeting main
  workflow_dispatch:           # Allows manual triggering

jobs:
  ci:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          
      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install ansible-core ansible-lint molecule

      - name: Install Ansible Collections
        run: ansible-galaxy collection install -r requirements.yml

      - name: Ansible Lint
        run: ansible-lint --fix . # Code quality check and fixing
      
      - name: Molecule Test
        run: molecule test  # Run Molecule tests